import { ShieldAlert } from 'lucide-react';

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto py-8 px-4 md:px-6">
      <header className="text-center mb-12">
        <ShieldAlert className="h-16 w-16 text-primary mx-auto mb-4" />
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl font-headline text-primary">
          Disclaimer
        </h1>
        <p className="mt-4 text-xl text-foreground/80 max-w-3xl mx-auto text-balance">
          Financial Projection & Simulation Disclaimer
        </p>
      </header>

      <div className="max-w-3xl mx-auto space-y-8 bg-card p-6 sm:p-8 rounded-xl shadow-lg text-foreground/80">
        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">1. For Informational Purposes Only</h2>
          <p className="leading-relaxed text-balance">
            The InferenceROI calculator and all associated content are provided for general informational and educational purposes only. The projections, calculations, and ROI estimates generated by this tool are simulations based on user-provided inputs and general market assumptions.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">2. No Financial Advice</h2>
          <p className="leading-relaxed text-balance">
            InferenceROI does not provide financial, investment, or professional business advice. The results should not be used as the sole basis for making hardware procurement or cloud infrastructure decisions. We recommend consulting with financial advisors and infrastructure engineers before making significant capital expenditures.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">3. Simulation Accuracy</h2>
          <p className="leading-relaxed text-balance">
            While we strive to provide accurate mathematical models, actual TCO (Total Cost of Ownership) may vary significantly due to fluctuations in electricity rates, hardware availability, maintenance costs, and cloud API pricing updates. InferenceROI is not liable for any discrepancies between our simulations and real-world costs.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">4. Hardware Presets</h2>
          <p className="leading-relaxed text-balance">
            Our "Local Dev Node" and other hardware presets are based on average performance and power specifications. Individual hardware performance, thermal throttling, and efficiency can vary by manufacturer and environment.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-foreground mb-3">5. Limitation of Liability</h2>
          <p className="leading-relaxed text-balance">
            In no event shall InferenceROI be liable for any financial losses, data loss, or infrastructure failures resulting from decisions made based on the information provided on this website.
          </p>
        </section>

        <p className="text-center font-semibold text-foreground/90 pt-4 border-t border-foreground/20">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </div>
    </div>
  );
}
